<a href="https://colab.research.google.com/github/dev-bhaveshye/Machine-Learning/blob/main/Constructing_own_Linear_Regression_Class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
class self_lr:

    def __init__(self):
        self.m = None
        self.b = None

    def fit(self , x_train,y_train):
          num=0
          den=0
          for i in range(x_train.shape[0]):
            num=num+((x_train[i]-x_train.mean())*(y_train[i]-y_train.mean()))
            den=den+((x_train[i]-x_train.mean())*(x_train[i]-x_train.mean()))
          self.m= num/den
          self.b= y_train.mean()-(self.m * x_train.mean())
          print("m is ",self.m)
          print("b is ",self.b)

    def predict(self,x_test):
          return "prediction of" , x_test , "is ",  self.m * x_test + self.b


In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/Salary_dataset.csv')


In [ ]:
df.head()

Unnamed: 0  YearsExperience   Salary
0           0              1.2  39344.0
1           1              1.4  46206.0
2           2              1.6  37732.0
3           3              2.1  43526.0
4           4              2.3  39892.0

In [ ]:
df.drop(columns=['Unnamed: 0'],inplace=True)

In [ ]:
x=df.iloc[:,0:1].values
y=df.iloc[:,1].values

In [ ]:
x

array([[ 1.2],
       [ 1.4],
       [ 1.6],
       [ 2.1],
       [ 2.3],
       [ 3. ],
       [ 3.1],
       [ 3.3],
       [ 3.3],
       [ 3.8],
       [ 4. ],
       [ 4.1],
       [ 4.1],
       [ 4.2],
       [ 4.6],
       [ 5. ],
       [ 5.2],
       [ 5.4],
       [ 6. ],
       [ 6.1],
       [ 6.9],
       [ 7.2],
       [ 8. ],
       [ 8.3],
       [ 8.8],
       [ 9.1],
       [ 9.6],
       [ 9.7],
       [10.4],
       [10.6]])

In [ ]:
import sklearn
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
y_train

array([122392., 109432.,  56958.,  39344.,  39892.,  66030.,  56643.,
        57082.,  55795., 101303.,  46206.,  37732., 105583.,  43526.,
        98274., 116970.,  81364., 121873.,  91739.,  54446.,  63219.,
        61112.,  93941.,  60151.])

In [ ]:
lr=self_lr()
lr.fit(x_train,y_train)

m is  [9423.81532303]
b is  [24380.20147947]


In [ ]:
x_test , y_test

(array([[9.7],
        [5. ],
        [8.3],
        [5.4],
        [3.3],
        [3.8]]),
 array([112636.,  67939., 113813.,  83089.,  64446.,  57190.]))

In [ ]:
lr.predict(x_test)

('prediction of',
 array([[9.7],
        [5. ],
        [8.3],
        [5.4],
        [3.3],
        [3.8]]),
 'is ',
 array([[115791.21011287],
        [ 71499.27809463],
        [102597.86866063],
        [ 75268.80422384],
        [ 55478.79204548],
        [ 60190.69970699]]))